### PR TITLE
adding robot control task

### PR DESCRIPTION
**Pull request by GPrathap**
- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Adding a different drive robot controller

### CODE REVIEW

**Review by marc-hanheide — APPROVED** [review]

**Comment by marc-hanheide** [comment]
I have merged, but I notice that the name may be misleading. As we are not using turtlebots, but this year we're using the Limos. Just to check with @GPrathap that the code is also aimed at and working with the Limo simulation?

**Comment by GPrathap** [comment]
Hi @marc-hanheide yeap can change velocity and odom topics, then it will be fine

**Comment by marc-hanheide** [comment]
I think the topic names are the same, it was just the name and the question if you have tested with the correct robot ;-)

**Comment by GPrathap** [comment]
I changed the package name and tested already before pushing https://github.com/LCAS/teaching/pull/41

**Pull request merged**
