### PR TITLE
Adding 3 mazes for testing the assignment

### PR DESCRIPTION
**Pull request by francescodelduchetto**
- each has its own launch file.
- each maze has a feasible solution.
- the best path has been marked with blue tiles in most switch points.

### CODE REVIEW

**Review by marc-hanheide — CHANGES_REQUESTED** [review]
there was a problem that your models contained also the robot model and the simulation state. I removed them. Somehow the editing you did in gazebo led to wrong coordinates and the simulation state is saved. I have corrected this and pushed to your branch, so this PR is correct now, but I think there is one issue here, the blue panels are visible from both sides of the wall. Was this the case for you as well? This can be wrong. Maybe if they are shifted slightly towards the right side of the wall (in the world files, not by mouse as this will lead to wrong states again, I fear)? What do you think. Please test my changes and think if my proposal could work?

**Comment by francescodelduchetto** [comment]
oh yes, I forgot to remove the robot model and I am not sure with what you mean with the simulation state. About the blue markers, you are right that its wrong if they are on both sides of the wall and I was careful in putting them only on one side, but I see that they are not in the models I pushed... I will fix them.

**Comment by marc-hanheide** [comment]
The problem was likely that if you just edit directly in gazebo and save it there, then the new position is saved in the `<state>` not the world. I had removed the `<state>` as that shouldn't be part of this, and hence may have removed your careful positioning, sorry. Better to edit the world files directly. I edit everything in gazebo and read the correct values in the Gazebo GUI. Then I round those values and put them manually in the `<pose>` of the respective `<model>` tags in the `world` files. Hope this helps.

**Comment by francescodelduchetto** [comment]
Okay, now they should be correct. I edited the files directly as you suggested, please check if it is okay.

 I noticed that when modifying the values from the GUI it doesn't always get updated in the pose in the rendering...it may well be that there is a bug also when saving the .world file from the gui and it doesn't save the most recent value after editing manually.

**Review by marc-hanheide — APPROVED** [review]

**Pull request merged**
